services:

# définition de notre image docker postgres.
  postgres:
    # Image permettant d'instancier une base de données PostgreSQL
    # contenant l'extension pgvector.
    image: pgvector/pgvector:pg17
    container_name: renlosey_vector_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - renlosey_vector_db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# définir un volume afin de faire persister nos données sur notre système.
volumes:
  renlosey_vector_db_volume: